import React from "react";
import MarketingApp from "./components/MarketingApp";
import Header from "./components/Header";
import { BrowserRouter } from "react-router-dom";
import {
  StylesProvider,
  createGenerateClassName,
} from "@material-ui/core/styles";

//  we are using createGenerateClassName as we are using same styling library(material-ui) for container and
// marketing app so when in production we build the css for the application due to the use of same libraries,
// it is likely the css names generated by the library(css-in-js library is getting used inside material-ui so chances are high
// that we'll have a minified class name that could collide between container app and marketing app)
// for both the application could collide and result in conflicting css
// so we are using createGenerateClassName to prevent those classname collision
const generateClassName = createGenerateClassName({
  productionPrefix: "co", // container
});

export default () => {
  return (
    <BrowserRouter>
      <StylesProvider generateClassName={generateClassName}>
        <div>
          <Header />
          <MarketingApp />
        </div>
      </StylesProvider>
    </BrowserRouter>
  );
};
