import React from "react";
import { Switch, Route, BrowserRouter } from "react-router-dom";
import {
  StylesProvider,
  createGenerateClassName,
} from "@material-ui/core/styles";

import Landing from "./components/Landing";
import Pricing from "./components/Pricing";

//  we are using createGenerateClassName as we are using same styling library(material-ui) for container and
// marketing app so when in production we build the css for the application due to the use of same libraries,
// it is likely the css names generated by the library(css-in-js library is getting used inside material-ui so chances are high
// that we'll have a minified class name that could collide between container app and marketing app)
// for both the application could collide and result in conflicting css
// so we are using createGenerateClassName to prevent those classname collision
const generateClassName = createGenerateClassName({
  productionPrefix: "ma", // marketing
});

export default () => {
  return (
    <div>
      <StylesProvider generateClassName={generateClassName}>
        <BrowserRouter>
          <Switch>
            <Route exact path="/pricing" component={Pricing} />
            <Route exact path="/" component={Landing} />
          </Switch>
        </BrowserRouter>
      </StylesProvider>
    </div>
  );
};
